ALTER TABLE "Clientes" DROP COLUMN IF EXISTS "telefono";
ALTER TABLE "Visitadores_Medicos" DROP COLUMN IF EXISTS "telefono";
ALTER TABLE "Proveedores" DROP COLUMN IF EXISTS "telefono";
ALTER TABLE "Usuarios" DROP COLUMN IF EXISTS "telefono";

CREATE TABLE "Telefonos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "numero" varchar(20) NOT NULL,
  "tipo" varchar NOT NULL CHECK ("tipo" IN ('móvil', 'fijo', 'otro')),
  "usuario_id" int,
  "proveedor_id" int,
  "visitador_id" int,
  "cliente_id" int
);

ALTER TABLE "Visitadores_Medicos" DROP CONSTRAINT IF EXISTS "Visitadores_Medicos_proveedor_id_fkey";
ALTER TABLE "Visitadores_Medicos" ADD FOREIGN KEY ("proveedor_id") REFERENCES "Proveedores" ("id");

ALTER TABLE "Telefonos" ADD FOREIGN KEY ("usuario_id") REFERENCES "Usuarios" ("id");
ALTER TABLE "Telefonos" ADD FOREIGN KEY ("proveedor_id") REFERENCES "Proveedores" ("id");
ALTER TABLE "Telefonos" ADD FOREIGN KEY ("visitador_id") REFERENCES "Visitadores_Medicos" ("id");
ALTER TABLE "Telefonos" ADD FOREIGN KEY ("cliente_id") REFERENCES "Clientes" ("id");

ALTER TABLE "Visitadores_Medicos" ADD FOREIGN KEY ("proveedor_id") REFERENCES "Proveedores" ("id");