CREATE TABLE "Roles" (
  "id" int PRIMARY KEY,
  "nombre" varchar(255) UNIQUE NOT NULL
);

CREATE TABLE "Permisos" (
  "id" int PRIMARY KEY,
  "nombre" varchar(255) UNIQUE NOT NULL,
  "descripcion" text
);

CREATE TABLE "Permisos_Roles" (
  "id" int PRIMARY KEY,
  "rol_id" int NOT NULL,
  "permiso_id" int NOT NULL
);

CREATE TABLE "Tipos_Movimientos_Inventario" (
  "id" int PRIMARY KEY,
  "nombre" varchar UNIQUE NOT NULL
);

CREATE TABLE "Categorias" (
  "id" int PRIMARY KEY,
  "nombre" varchar(100) UNIQUE NOT NULL
);

CREATE TABLE "Proveedores" (
  "id" int PRIMARY KEY,
  "nombre" varchar(255) UNIQUE NOT NULL,
  "direccion" varchar(255) NOT NULL,
  "correo" varchar(255) UNIQUE,
  "telefono" varchar(50)
);

CREATE TABLE "Estados_Calendarios" (
  "id" int PRIMARY KEY,
  "nombre" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "Usuarios" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "nombre" varchar NOT NULL,
  "apellidos" varchar NOT NULL,
  "rol_id" int NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "status" varchar NOT NULL CHECK ("status" IN ('activo', 'inactivo')),
  "local" int,
  "contraseña" varchar NOT NULL,
  "fechaNacimiento" date NOT NULL,
  "creacion" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "telefono" varchar(50)
);

CREATE TABLE "Locales" (
  "id" int PRIMARY KEY,
  "administrador_id" int,
  "nombre" varchar(255) NOT NULL,
  "direccion" varchar(255),
  "nit_emisor" varchar(255)
);

CREATE TABLE "Clientes" (
  "id" int PRIMARY KEY,
  "nombre" varchar(255) NOT NULL,
  "nit" varchar(50) UNIQUE NOT NULL,
  "direccion" varchar(255),
  "correo" varchar(255) UNIQUE,
  "telefono" varchar(50)
);

CREATE TABLE "Productos" (
  "codigo" int PRIMARY KEY,
  "nombre" text UNIQUE NOT NULL,
  "presentacion" varchar(255) NOT NULL,
  "proveedor_id" int NOT NULL,
  "precioVenta" numeric(10,2) NOT NULL,
  "precioCosto" numeric(10,2) NOT NULL,
  "receta" boolean NOT NULL,
  "stock_minimo" int NOT NULL,
  "detalles" text
);

CREATE TABLE "Promociones" (
  "id" int PRIMARY KEY,
  "descripcion" text NOT NULL,
  "descuento" numeric(5,2) NOT NULL,
  "fecha_inicio" timestamp NOT NULL,
  "fecha_final" timestamp NOT NULL
);

CREATE TABLE "Visitadores_Medicos" (
  "id" int PRIMARY KEY,
  "nombre" varchar(255) NOT NULL,
  "proveedor_id" int,
  "correo" varchar(255) UNIQUE,
  "telefono" varchar(50),
  FOREIGN KEY ("proveedor_id") REFERENCES "Proveedores" ("id")
);

CREATE TABLE "Lotes" (
  "id" int PRIMARY KEY,
  "producto_id" int NOT NULL,
  "lote" varchar(255) NOT NULL,
  "fecha_vencimiento" date NOT NULL
);

CREATE TABLE "Ventas" (
  "id" int PRIMARY KEY,
  "cliente_id" int NOT NULL,
  "total" numeric(10,2) NOT NULL,
  "tipo_pago" varchar NOT NULL CHECK ("tipo_pago" IN ('efectivo', 'tarjeta', 'transacción'))
);

CREATE TABLE "Compras" (
  "id" int PRIMARY KEY,
  "no_factura" int UNIQUE NOT NULL,
  "usuario_id" int NOT NULL,
  "proveedor_id" int,
  "total" numeric NOT NULL,
  "credito" boolean NOT NULL,
  "descripcion" text
);

CREATE TABLE "Pagos_Compras" (
  "id" int PRIMARY KEY,
  "compra_id" int NOT NULL,
  "cuotas" int NOT NULL,
  "estado" varchar NOT NULL CHECK ("estado" IN ('pendiente', 'pagado')),
  "total" numeric(10,2) NOT NULL,
  "fecha" timestamp NOT NULL,
  "detalles" text
);

CREATE TABLE "Inventario" (
  "id" int PRIMARY KEY,
  "lote_id" int NOT NULL,
  "cantidad" int NOT NULL,
  "tipo_movimiento_id" int NOT NULL,
  "venta_id" int,
  "compra_id" int,
  "precio_venta" numeric(10,2) NOT NULL,
  "precio_costo" numeric(10,2) NOT NULL,
  "local_id" int NOT NULL,
  "encargado_id" int NOT NULL,
  "fecha" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE "Facturas" (
  "id" int PRIMARY KEY,
  "venta_id" int NOT NULL,
  "local_id" int NOT NULL,
  "no_serie" varchar(255) UNIQUE NOT NULL,
  "numero_dte" int NOT NULL,
  "autorizacion" varchar(255) NOT NULL,
  "moneda" varchar(100) NOT NULL,
  "fecha_emsion" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "fecha_certificacion" timestamp
);

CREATE TABLE "Recetas" (
  "id" int PRIMARY KEY,
  "producto_id" int NOT NULL,
  "venta_id" int NOT NULL,
  "archivo" text NOT NULL
);

CREATE TABLE "Documentos_Locales" (
  "id" int PRIMARY KEY,
  "nombre" varchar(255) NOT NULL,
  "usuario_id" int NOT NULL,
  "archivo" text NOT NULL,
  "local_id" int NOT NULL,
  "creacion" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "vencimiento" date
);

CREATE TABLE "Promociones_Producto" (
  "id" int PRIMARY KEY,
  "producto_id" int NOT NULL,
  "promocion_id" int NOT NULL
);

CREATE TABLE "Categorias_Productos" (
  "id" int PRIMARY KEY,
  "categoria_id" int NOT NULL,
  "producto_id" int NOT NULL
);

CREATE TABLE "Catalogos_Visitadores" (
  "id" int PRIMARY KEY,
  "visitador_id" int NOT NULL,
  "archivo" text NOT NULL
);

CREATE TABLE "Calendario" (
  "id" int PRIMARY KEY,
  "usuario_id" int NOT NULL,
  "visitador_id" int,
  "titulo" varchar(250) NOT NULL,
  "estado_id" int NOT NULL,
  "detalles" text,
  "fecha" timestamp NOT NULL
);

ALTER TABLE "Lotes" ADD FOREIGN KEY ("producto_id") REFERENCES "Productos" ("codigo");
ALTER TABLE "Productos" ADD FOREIGN KEY ("proveedor_id") REFERENCES "Proveedores" ("id");
ALTER TABLE "Facturas" ADD FOREIGN KEY ("venta_id") REFERENCES "Ventas" ("id");
ALTER TABLE "Facturas" ADD FOREIGN KEY ("local_id") REFERENCES "Locales" ("id");
ALTER TABLE "Compras" ADD FOREIGN KEY ("proveedor_id") REFERENCES "Proveedores" ("id");
ALTER TABLE "Pagos_Compras" ADD FOREIGN KEY ("compra_id") REFERENCES "Compras" ("id");
ALTER TABLE "Locales" ADD FOREIGN KEY ("administrador_id") REFERENCES "Usuarios" ("id");
ALTER TABLE "Inventario" ADD FOREIGN KEY ("encargado_id") REFERENCES "Usuarios" ("id");
ALTER TABLE "Permisos_Roles" ADD FOREIGN KEY ("permiso_id") REFERENCES "Permisos" ("id");
ALTER TABLE "Permisos_Roles" ADD FOREIGN KEY ("rol_id") REFERENCES "Roles" ("id");
ALTER TABLE "Catalogos_Visitadores" ADD FOREIGN KEY ("visitador_id") REFERENCES "Visitadores_Medicos" ("id");
ALTER TABLE "Compras" ADD FOREIGN KEY ("usuario_id") REFERENCES "Usuarios" ("id");
ALTER TABLE "Recetas" ADD FOREIGN KEY ("producto_id") REFERENCES "Productos" ("codigo");
ALTER TABLE "Recetas" ADD FOREIGN KEY ("venta_id") REFERENCES "Ventas" ("id");
ALTER TABLE "Documentos_Locales" ADD FOREIGN KEY ("usuario_id") REFERENCES "Usuarios" ("id");
ALTER TABLE "Documentos_Locales" ADD FOREIGN KEY ("local_id") REFERENCES "Locales" ("id");
ALTER TABLE "Categorias_Productos" ADD FOREIGN KEY ("categoria_id") REFERENCES "Categorias" ("id");
ALTER TABLE "Categorias_Productos" ADD FOREIGN KEY ("producto_id") REFERENCES "Productos" ("codigo");
ALTER TABLE "Ventas" ADD FOREIGN KEY ("cliente_id") REFERENCES "Clientes" ("id");
ALTER TABLE "Promociones_Producto" ADD FOREIGN KEY ("producto_id") REFERENCES "Productos" ("codigo");
ALTER TABLE "Promociones_Producto" ADD FOREIGN KEY ("promocion_id") REFERENCES "Promociones" ("id");
ALTER TABLE "Calendario" ADD FOREIGN KEY ("usuario_id") REFERENCES "Usuarios" ("id");
ALTER TABLE "Calendario" ADD FOREIGN KEY ("visitador_id") REFERENCES "Visitadores_Medicos" ("id");
ALTER TABLE "Inventario" ADD FOREIGN KEY ("local_id") REFERENCES "Locales" ("id");
ALTER TABLE "Inventario" ADD FOREIGN KEY ("tipo_movimiento_id") REFERENCES "Tipos_Movimientos_Inventario" ("id");
ALTER TABLE "Inventario" ADD FOREIGN KEY ("lote_id") REFERENCES "Lotes" ("id");
ALTER TABLE "Calendario" ADD FOREIGN KEY ("estado_id") REFERENCES "Estados_Calendarios" ("id");
ALTER TABLE "Usuarios" ADD FOREIGN KEY ("rol_id") REFERENCES "Roles" ("id");
ALTER TABLE "Inventario" ADD FOREIGN KEY ("venta_id") REFERENCES "Ventas" ("id");
ALTER TABLE "Inventario" ADD FOREIGN KEY ("compra_id") REFERENCES "Compras" ("id");